server:
  port: 8001

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#服务的名称
spring:
  application:
    name: product-service

name_server: 10.211.55.18:9876
order_topic: order


